### ISSUE TITLE
I want to join your team

### ISSUE THREAD

**Issue by kcraftcode** [Goopper/platform-frontend#54]
As an experienced blockchain and web full-stack developer, I am looking for projects where I can leverage my expertise in decentralized applications, smart contracts, and blockchain integration to drive innovative solutions and contribute to your success. With extensive experience in boosted chains, games, DeFi, NFTs, marketplaces, gambling, tokens, social platforms, high-risk projects, and miscellaneous applications, I am eager to contribute to your project with my skills and experience.

**Comment by CHENPrime-coder** [comment]
抱歉，直到今天我才看见你的issues。这个项目是我们毕业设计，早在6月初就基本开发完毕了，在这之后我们也没有继续关注过这个项目了😂

Sorry, I didn't see your issues until today. this project was our graduation project, which was basically developed at the beginning of June, and we haven't continued to focus on it since then😂
